<a href="https://colab.research.google.com/github/mfdev-solution/collab_deep_lerning/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

More specificatlly ,we're going to cover:
* introduction to tensor
* Gtting information from tensors
* Manipulation tensors 
* Tensors and Numpy
* useing @tf.funciton (a way to speed up your regular python function s)
* Using GPUs with TensorFlow
* Exercises to try for yourself

#introduction t otensors 

In [ ]:
import tensorflow as tf
print(tf.__version__)

2.9.2


In [ ]:
#creating tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
#check number of dimensions
scalar.ndim

0

In [ ]:
#create a vector
vector = tf.constant([10,10])
vector.ndim

1

In [ ]:
from numpy import float32
#create a matrix 
matrix = tf.constant([[10,7],[20,3]])
matrix.ndim
another_matrix = tf.constant([[10.,7.],[4.,8.],[2,5]],dtype=float32)
another_matrix.ndim

2

In [ ]:
#tensor = ts.constant()

In [ ]:
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,8])
changeable_tensor,unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  8], dtype=int32)>)

In [ ]:
changeable_tensor[0].assign(9)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([9, 7], dtype=int32)>

#Random tensors


In [ ]:
from tensorflow._api.v2 import random
#creating random tensors
random_1 = tf.random.Generator.from_seed(40)
random_1 = random_1.normal(shape=(3,2))
random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 0.78953624,  0.53897345],
       [-0.48535708,  0.74055266],
       [ 0.31662667, -1.4391748 ]], dtype=float32)>

In [ ]:
#Shuffle a tensor 
not_shuffled = tf.constant([[10,7]
                           ,[3,9]
                           ,[2,5]])
not_shuffled.ndim
 

2

In [ ]:
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled,seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  9],
       [ 2,  5]], dtype=int32)>

In [ ]:
#creating a tensor of ones 

#import numpy as np
tf.ones([5,4],dtype=float)

<tf.Tensor: shape=(5, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

### Turn Numpy arrays into tensors

In [ ]:
import array
import numpy as np
np_array = np.arange(1,25 , dtype= np.int32)
np_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
A = tf.constant(np_array,shape=(3,8))
A
B = tf.constant(np_array , shape=(3,4,2))
B

<tf.Tensor: shape=(3, 4, 2), dtype=int32, numpy=
array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12],
        [13, 14],
        [15, 16]],

       [[17, 18],
        [19, 20],
        [21, 22],
        [23, 24]]], dtype=int32)>

###getting information from tensors 
When dealing with tensors you probably want to be aware  of the following attributes :
* shape 
* Rank
* Axisi or demension
* Size 

In [ ]:
#creating a rank 4 tenrs
rank_4_tensor = tf.zeros(shape=[2,3,4,5])
rank_4_tensor 

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
### Get various attributs of our tensor
print("Datatype of every elements :" , rank_4_tensor.dtype)
print("Number of dimensions (rand)",rank_4_tensor.ndim)
print("Shape of tensor : ",rank_4_tensor.shape)
print("Total number of elemens : ",tf.size(rank_4_tensor).numpy())

Datatype of every elements : <dtype: 'float32'>
Number of dimensions (rand) 4
Shape of tensor :  (2, 3, 4, 5)
Total number of elemens :  120


#indexing and expanding tensors
*Tensors can be indexed just like python list

In [ ]:
rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

#Manipulation tensors
**Basic opreations**

In [ ]:
#you cad add values to a tensor by using the addition operator
tensor = tf.constant([[10,7],[7,3]])
tensor + 2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[12,  9],
       [ 9,  5]], dtype=int32)>

**Matrix Multiplication**

In [ ]:
#matrix multiplication in tensorflow
print(tensor)
tf.matmul(tensor,tensor)

tf.Tensor(
[[10  7]
 [ 7  3]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[149,  91],
       [ 91,  58]], dtype=int32)>

In [ ]:
#to multiply two matrixes we use @ instead of *
tensor @ tensor
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7,  3]], dtype=int32)>

In [ ]:
#Perform matrix multiplication betwene X et Y (transposed)
tensor = tf.constant([[10,7,4],[7,3,4],[12,5,8]])
tf.transpose(tensor)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[10,  7, 12],
       [ 7,  3,  5],
       [ 4,  4,  8]], dtype=int32)>

# Agregating tensors

In [ ]:
D  = tf.constant([
  [[1, 2], [3, 4]],
  [[1, 2], [3, 4]]
])
D
tf.abs(D)

In [ ]:
print(tf.math.reduce_max(D))#find the max
print(tf.math.reduce_min(D))#find the min
print(tf.math.reduce_mean(D))#find the mean
print(tf.math.reduce_sum(D)) #find the sum
print(tf.math.reduce_std(tf.cast(D,dtype=float32))) #find the deviation
print(tf.math.reduce_variance(tf.cast(D,dtype=tf.float32))) #find the variance

tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(20, shape=(), dtype=int32)
tf.Tensor(1.118034, shape=(), dtype=float32)
tf.Tensor(1.25, shape=(), dtype=float32)


**Finding the posittional of minimun or maximun**

In [ ]:
#create a new tensor for finding a minimun or a maximum
tf.random.set_seed(43)
F = tf.random.uniform(shape=[50])


<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.2733041 , 0.5020257 , 0.6628481 , 0.6473899 , 0.3857293 ,
       0.36172044, 0.5412978 , 0.48597205, 0.8773687 , 0.19192028,
       0.9264002 , 0.89626896, 0.6672703 , 0.47216296, 0.22052324,
       0.88224113, 0.21332026, 0.3742751 , 0.6198429 , 0.67401516,
       0.33629417, 0.04864144, 0.00223255, 0.9375315 , 0.1595205 ,
       0.76488817, 0.5631764 , 0.48775423, 0.4250028 , 0.29910493,
       0.8409952 , 0.6727512 , 0.00153816, 0.4085456 , 0.9261861 ,
       0.18742752, 0.60272205, 0.99417937, 0.42423892, 0.27978897,
       0.9430332 , 0.80545497, 0.06359637, 0.56783044, 0.26592016,
       0.98973536, 0.5452112 , 0.11514163, 0.53635466, 0.6935723 ],
      dtype=float32)>

In [ ]:
#find the positional of the maximum

tf.math.reduce_max(F)
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=37>

In [ ]:
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.99417937>

#Squeezing a tensor (removing all single dimensions 

In [ ]:
tf.random.set_seed(43)
G = tf.constant(tf.random.uniform(shape=[50] ),shape=(1,1,1,1,50))

#one-hot incoding

In [ ]:
#create a list of indices 
some_list = [0,1,2,3]
tf.one_hot(some_list , depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [ ]:
#specify custom values for one hot_encoding
tf.one_hot(some_list , depth=4, on_value="you I love deep learnig ",off_value="I also like to play soccer")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'you I love deep learnig ', b'I also like to play soccer',
        b'I also like to play soccer', b'I also like to play soccer'],
       [b'I also like to play soccer', b'you I love deep learnig ',
        b'I also like to play soccer', b'I also like to play soccer'],
       [b'I also like to play soccer', b'I also like to play soccer',
        b'you I love deep learnig ', b'I also like to play soccer'],
       [b'I also like to play soccer', b'I also like to play soccer',
        b'I also like to play soccer', b'you I love deep learnig ']],
      dtype=object)>

In [ ]:
some_text = ['reg','green','blue']
tf.one_hot(some_list, depth=4 , axis=0)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>